mode: backtest
start_date: 2025-04-01
end_date: 2025-05-01
primary_interval: 1h
initial_cash: 100000
margin_requirement: 0.0
show_reasoning: false
show_agent_graph: true
signals:
  intervals: ["1h"]
  tickers: ["BTCUSDT"]
  strategies: ['MacdStrategy']
# , "RSIStrategy"]
model:
  name: "gpt-4o-mini" # choose your model.
  provider: "openai"  # llm provider.
  base_url: "https://api.openai.com/v1"  # you can change it to your own.

